// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for windows - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyDQhMCZSv0stgMHYQtn_wO5yZRUJSPJpoU',
  //   appId: '1:34522657374:web:1e59842788eb4c3e373acf',
  //   messagingSenderId: '34522657374',
  //   projectId: 'chairy-firebase-dev',
  //   authDomain: 'chairy-firebase-dev.firebaseapp.com',
  //   storageBucket: 'chairy-firebase-dev.appspot.com',
  //   measurementId: 'G-EZ709LLM0C',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfHNkI_p_TLfD5OXrRR-_6o4wo3_ysWJQ',
    appId: '1:861185321003:android:8909265d0031ce0036a26e',
    messagingSenderId: '861185321003',
    projectId: 'beasy-2e75f',
    storageBucket: 'beasy-2e75f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDH76bJ-Mog_3dZWp3X37iASTM851keXo',
    appId: '1:861185321003:ios:6db7fe39c437e0a436a26e',
    messagingSenderId: '861185321003',
    projectId: 'beasy-2e75f',
    storageBucket: 'beasy-2e75f.appspot.com',
    iosBundleId: 'com.techdot.beasy',
  );
}
